### ISSUE TITLE
Add ability to get shopping carts view as well as order view

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-cart#1]
@OlegoO commented on [Wed Aug 02 2017](https://github.com/VirtoCommerce/vc-platform/issues/1103)

We want to get shopping carts view in admin as well as order view.

Version info: 
- Module version: v2.16.0

### Expected behavior
1. Get cart blade with filters, sortings and etc
2. See customer cart (Status, LineItems, Payments)

### Actual behavior
Not implemented yet

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-104
