### ISSUE TITLE
Extension property in the Cart line item is insert as NULL when adding a new cart line item

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-module-cart#100]
Hello Team,

I have created a new module to create an extension for the cart line item to add one additional column.
I have followed the extensions code available in the demo feature solutions.
I am able to generate the new column in the cart line item table. I added the new property also into the  ToModel, fromModel and patch methods in the entity. Then I override the classes in the module.cs file.
In Virto Cart module APIs swagger schema, I am able to see the new column there. But when I passed the field in the payload, it is storing as null. I also debugged the Virto Cart module and I am able to see the new property in the original entity after the patch method calls in line 102 and also in changed entries. But after the commit async method is called, the value is insert as NULL in the property.

![image](https://user-images.githubusercontent.com/71070755/170134332-fada4d89-51d3-46c7-8371-bd2a8dd568fb.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8044 has been created

**Comment by OlegoO** [comment]
Original response here
https://www.virtocommerce.org/t/value-is-inserting-as-null-in-cart-line-item-extension-property/456/2
