### ISSUE TITLE
Dynamic property values for line items are not deleted

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-cart#12]
When I remove a line item from the cart and then save the cart, the line item's dynamic property values are not deleted and stay in the database forever, referencing the nonexistent line item.

**Comment by tatarincev** [comment]
Technical solution for this problem I see in creation the new  OrderChanged event handler where the need to detect deleted cart items by comparing `Old` and `Changed` carts objects and removing dynamic properties for these objects.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-cart/releases/edit/v2.16.10
