### ISSUE TITLE
Possible error when adding shipment to cart

### ISSUE THREAD

**Issue by azapotoczny-forte** [VirtoCommerce/vc-module-cart#126]
When adding the shipment to the shopping cart using `CartModuleController.AddOrUpdateCartShipment` I got the error:
```
Unknown shipment method: MyMethod with option: MyOption
```

I have more than one shipping methods registered, but some of them are not configured and not activated. I checked the code and it looks like the problem is the method `ShoppingCartBuilder.GetShippingRatesAsync`.  There is a lookup there that returns more than one method, and the first method might be different than specified in the `shippingMethodCode` argument. See the code:

```
public override async Task<ICollection<ShippingRate>> GetShippingRatesAsync(string shippingMethodCode)
{
    var shippingEvaluationContext = new ShippingEvaluationContext(this.Cart);

    var criteria = new ShippingMethodsSearchCriteria
    {
        IsActive = true,
        Take = int.MaxValue,
        StoreId = this.Store.Id,
        Codes = new[] { shippingMethodCode },
    };

   // Wrong method is picked up here
    var shippingMethod = (await this.shippingMethodsSearchService.SearchShippingMethodsAsync(criteria))
        .Results.FirstOrDefault();

    return shippingMethod?.CalculateRates(shippingEvaluationContext).ToList();
}
````

I think the transient methods should be ignored in this case, which means that the criteria should look like this:
```
var criteria = new ShippingMethodsSearchCriteria
{
    IsActive = true,
    Take = int.MaxValue,
    StoreId = this.Store.Id,
    Codes = new[] { shippingMethodCode },
    WithoutTransient = true // Ignore transient methods here
};
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8427 has been created

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-cart/releases/tag/3.401.0, fix delivered to two latest releases as well.
