### ISSUE TITLE
Cart returned without recalculated totals

### ISSUE THREAD

**Issue by azapotoczny-forte** [VirtoCommerce/vc-module-cart#127]
When fetching the shopping cart using `CartModuleController.GetCartById` the totals are set to zero. This endpoint loads the cart using `CartResponseGroup.Full`. However, the class `ShoppingCartService` seems to have a bug in the `ProcessModel` method:
```
protected override ShoppingCart ProcessModel(string responseGroup, ShoppingCartEntity entity, ShoppingCart model)
{
    //Calculate totals only for full responseGroup
    if (responseGroup == null)
    {
        _totalsCalculator.CalculateTotals(model);
    }
    model.ReduceDetails(responseGroup);
    return model;
}
```

I guess the code should look like this:

```
protected override ShoppingCart ProcessModel(string responseGroup, ShoppingCartEntity entity, ShoppingCart model)
{
    //Calculate totals only for full responseGroup
    if (responseGroup == null || responseGroup == CartResponseGroup.Full.ToString()) 
    {
        _totalsCalculator.CalculateTotals(model);
    }
    model.ReduceDetails(responseGroup);
    return model;
}
```

I assume that not specified response group (null) means Full.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8426 has been created

**Comment by OlegoO** [comment]
Created https://github.com/VirtoCommerce/vc-module-experience-api/pull/522

**Comment by OlegoO** [comment]
Created https://github.com/VirtoCommerce/vc-module-cart/pull/148

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-cart/releases/tag/3.809.0
