### ISSUE TITLE
CartChangedEvent.NewEntry.DynamicProperties always null 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-cart#13]
- Steps to reproduce

0. create a new cart with dynamic properties 
1. get cart id and get cart by id from cart API
2. send this cart to: PUT /api/carts (in swagger?)

In the emitted `CartChangedEvent.NewEntry.DynamicProperties` will has a null value

**Comment by eMazeika** [comment]
originally the issue was about CartChangeEvent, not CartChangedEvent. We should probably check them both. @MalikJuly , could you reproduce it?

**Comment by asvishnyakov** [comment]
@eMazeika May you test it locally with dev branch of this module? For me looks it may relate d1cf456

**Comment by MalikJuly** [comment]
I'll try to reproduce it locally with dev branch

**Comment by eMazeika** [comment]
The original issue seems to be resolved in related commit in dev branch. We need to see that released for our project.
@MalikJuly , is the "Dynamic properties not saved in DB" a new issue that you're going to solve?

**Comment by asvishnyakov** [comment]
@tatarincev If all is ok, then make release please

**Comment by eMazeika** [comment]
Actually, after the mentioned fix was applied, the emitted CartChangedEvent.OldEntry.DynamicProperties is null

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-cart/releases/v2.16.13
