### ISSUE TITLE
Failed executing DbCommand during CartAddress INSERT Operation in UpdateShoppingCart Method

### ISSUE THREAD

**Issue by Kirubha-A** [VirtoCommerce/vc-module-cart#144]
I am encountering an issue where a DbCommand fails during the INSERT operation into the CartAddress table while updating a shopping cart. This occurs in the UpdateShoppingCart method of the VirtoCommerce.CartModule.Web.Controllers.Api.CartModuleController class.

Failed executing DbCommand (2ms) [Parameters=[@p0='?' (Size = 128), @p1='?' (Size = 32), @p2='?' (Size = 128), @p3='?' (Size = 3), @p4='?' (Size = 64), @p5='?' (Size = 254), @p6='?' (Size = 64), @p7='?' (Size = 64), @p8='?' (Size = 2048), @p9='?' (Size = 2048), @p10='?' (Size = 2048), @p11='?' (Size = 64), @p12='?' (Size = 128), @p13='?' (Size = 128), @p14='?' (Size = 64), @p15='?' (Size = 64), @p16='?' (Size = 128), @p17='?' (Size = 128), @p18='?' (Size = 128), @p19='?' (Size = 128)], CommandType='Text', CommandTimeout='4200']
SET NOCOUNT ON;
INSERT INTO [CartAddress] ([Id], [AddressType], [City], [CountryCode], [CountryName], [Email], [FirstName], [LastName], [Line1], [Line2], [Name], [Organization], [OuterId], [PaymentId], [Phone], [PostalCode], [RegionId], [RegionName], [ShipmentId], [ShoppingCartId])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19);

I would appreciate any guidance or suggestions to resolve this issue. If additional information is needed, please let me know.

Thank you

**Comment by p10** [comment]
use code blocks

**Comment by OlegoO** [comment]
@Kirubha-A Could you add more information about the error? call stack? which version of platform and cart module do you use
