### ISSUE TITLE
Allow to specify multiple member ids in search criteria

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-cart#15]
@asvishnyakov commented on [Mon May 28 2018](https://github.com/VirtoCommerce/vc-module-core/issues/62)

For B2B scenarios, we may want to allow share lists between organization members. So, allow to specify multiple member ids in cart search criteria.

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-cart/releases/v2.16.9
