### ISSUE TITLE
Bug in ShippingTotalWithTax calculation

### ISSUE THREAD

**Issue by megafreeman** [VirtoCommerce/vc-module-cart#26]
https://github.com/VirtoCommerce/vc-module-cart/blob/01635feb96a92a249bdbe3f3ab93b996273007b7/VirtoCommerce.CartModule.Data/Services/DefaultShopingCartTotalsCalculator.cs#L120

Should be:
cart.ShippingTotalWithTax = Math.Round(cart.ShippingTotal**WithTax**, 2, MidpointRounding.AwayFromZero);

Also, need to actualize unit tests to cover this case which will prevent recurrence it in the future.

**Comment by tatarincev** [comment]
Thanks a lot for bug report

**Comment by tatarincev** [comment]
@ilyawzrd Could you extend this test https://github.com/VirtoCommerce/vc-module-cart/blob/master/VirtoCommerce.CartModule.Test/CartTotalsCalculationTests.cs check the correctness of this property calculation?

**Comment by yecli** [comment]
Was released in [v2.16.15](https://github.com/VirtoCommerce/vc-module-cart/releases/tag/v2.16.15).
