### ISSUE TITLE
Cannot insert the value NULL into column 'LineItemId', table 'dbo.CartShipmentItem'; column does not allow nulls.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-cart#29]
Fixed by this commit https://github.com/VirtoCommerce/vc-module-cart/commit/6a1272621ab77691b56440124b0a45f79bf22c49

**Comment by yecli** [comment]
It was released in [v2.16.15](https://github.com/VirtoCommerce/vc-module-cart/releases/tag/v2.16.15)
