### ISSUE TITLE
Error: Currency must be a string with a maximum length of 3.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-cart#3]
Validation failed for one or more entities. See 'EntityValidationErrors' property for more details. The field Currency must be a string with a maximum length of 3.

### Expected behavior
Add validator and don't allow to create a Currency code with length != 3 
OR 
Remove EntityValidation 

### Actual behavior
I can set any currency code, but then get 'EntityValidationErrors' 

### Steps to reproduce
1. Create a currency code with EURO code
2. Go to store and select EURO 
3. Try to add product into cart

``````````
Validation failed for one or more entities. See 'EntityValidationErrors' property for more details. The field Currency must be a string with a maximum length of 3.

System.ServiceModel.FaultException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
The field Currency must be a string with a maximum length of 3.
   at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex)
   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository)
   at VirtoCommerce.CartModule.Data.Services.ShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts)
   at VirtoCommerce.CartModule.Web.Controllers.Api.CartModuleController.Create(ShoppingCart cart)
   at lambda_method(Closure , Object , Object[] )

``````````

**Comment by zhangpengchen** [comment]
Actually I want to add **Points** as a currency also.

**Comment by zhangpengchen** [comment]
@tatarincev this will work, we can use 2 or 3 chars for currency code. 
In your screenshot you can fill in **Points** as a currency code, there is no validation, that is why we thought the system may want to support more than 3 letters.

**Comment by tatarincev** [comment]
if it's only about validation in the UI, then there's no problem!

**Comment by pushnitsa** [comment]
Fixed in the module-core [repository](https://github.com/VirtoCommerce/vc-module-core).

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.1
