### ISSUE TITLE
AddCartCoupon(string cartId, string couponCode) does not save the cart.

### ISSUE THREAD

**Issue by bjornstromblom** [VirtoCommerce/vc-module-cart#30]
Using the API i post a valid cartId and a couponCode, no errors are thrown but the coupon is not saved on the cart.

**Comment by yecli** [comment]
Could you provide more details: versions, expected and actual behavior, sequence of actions to reproduce the problem?

In case you need an example of how to work with the cart, these are the API calls that comes to storefront:
POST: /storefront/Electronics/en-US/storefrontapi/cart/coupons/validate
POST: /storefront/Electronics/en-US/storefrontapi/cart/coupons/test
GET: /storefront/Electronics/en-US/storefrontapi/cart
For more details you could check their code.
If you need specific platform actions, you could check storefront calls to platform (using Fiddler. for example).

**Comment by bjornstromblom** [comment]
Ok, sorry about that.

We don't use your storfront, but we use the APIs.

**Versions** (as of this writing latest on all modules)
Core Module 2.25.17 
Marketing Module 2.17.2 
Shopping Cart Module 2.16.16

**Steps to reproduce**
GET /api/carts/{cartId} - With a valid cartId, the Cart is returend without any promotions added.
POST /api/carts/{cartId}/coupons/{couponCode} - With the same cartId and a valid couponCode, the return is as expected: 204 | No Content
GET /api/carts/{cartId} - The cart shows no coupon.

I hade a look at the code in [CartModuleController.cs#160](https://github.com/VirtoCommerce/vc-module-cart/blob/master/VirtoCommerce.CartModule.Web/Controllers/Api/CartModuleController.cs#L160) and then ran the debugger and everything looks fine. But the Coupon is not saved to the Cart.
