### ISSUE TITLE
Empty collection request optimization

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-cart#34]
In [CartRepositoryImpl.GetShoppingCartsByIds](https://github.com/VirtoCommerce/vc-module-cart/blob/8d035c1c1f5d127990bb797d7e9ec65347ea28a1/VirtoCommerce.CartModule.Data/Repositories/CartRepositoryImpl.cs#L184) when we are getting empty `string[] ids` array many redundant queries are performed.

To avoid these "empty" queries we could check parameter collection for emptiness using [IsNullOrEmpty extension method](https://github.com/VirtoCommerce/vc-platform/blob/853d66a976c47bf8d7b2c5222c6acf2bfc720915/VirtoCommerce.Platform.Core/Common/EnumerableExtensions.cs#L14). If it is empty - do not execute queries, just return empty collection.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-cart/releases/tag/v2.16.17
