### ISSUE TITLE
Extend the shopping cart persistent model to support  multiple coupons

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-cart#6]
In current version the ShoppingCartEntity model has only one coupon:
```csharp
[StringLength(64)]
public string Coupon { get; set; }
```

Need to change it to a collection.

**Comment by tatarincev** [comment]
Techincal tips:

https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/managing-module-database

 ```Add-Migration MyMigration -ConnectionString 'Data Source=(local);Initial Catalog=VirtoCommerce2;Persist Security Info=True;User ID=virto;Password=virto;MultipleActiveResultSets=True;Connect Timeout=420' -ConnectionProviderName System.Data.SqlClient
```

**Comment by tatarincev** [comment]
Need to extend ShopingCart persistent model with new table 
![image](https://user-images.githubusercontent.com/7566324/44900082-f616da00-ad03-11e8-81db-e17b7e23b02e.png)
To allow store multiple coupons entered for cart

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-cart/releases/tag/v2.16.14
