### ISSUE TITLE
Tax Percent fraction is lost when saving into database

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce/vc-module-cart#7]
Using Rate = "7.25" for an example.

This is how it looks in UI:
![image](https://user-images.githubusercontent.com/20122385/36962561-bbf666c0-2058-11e8-815e-f1d233cf24d7.png)

This is what being stored in CartLineItem table:
![untitled-asd](https://user-images.githubusercontent.com/20122385/36962671-29a6ac20-2059-11e8-8f2c-ec9dff4db532.png)

This is how it looks in the checkout:
![image](https://user-images.githubusercontent.com/20122385/36962745-73e23804-2059-11e8-8102-b1cfbdf92c85.png)

Possible related issue and solution for EFCore but might be relevant in this case
https://github.com/aspnet/EntityFrameworkCore/issues/6538

**Comment by tatarincev** [comment]
Released
https://github.com/VirtoCommerce/vc-module-cart/releases/tag/v2.16.6
